import { Header } from '@/components/Header'
import './globals.css'
import { Lato } from 'next/font/google'

const lato = Lato({
  weight: ['300', '400', '700'],
  subsets: ['latin']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={lato.className}>
        <Header />
        {children}</body>
    </html>
  )
}